### PR TITLE
Feature/fix for java library plugin

### LINKED ISSUE #72: Gradle 3.4.1 - Support new configurations in 'java-library' within MavenResolvedDependenciesPlugin
Since Gradle 3.4, 'java-library' adds new configurations which don't seem to get picked up when MavenResolvedDependencies resolves dependencies.  The result is that if e.g. dependency-recommender is used with java-library, the resulting POMs omit version strings.

I'm not sure the best approach here; It seems like in addition to runtime configuration the runtimeClasspath configuration needs to be appended (and maybe compileClasspath?):

https://github.com/nebula-plugins/nebula-publishing-plugin/blob/master/src/main/groovy/nebula/plugin/publishing/maven/MavenResolvedDependenciesPlugin.groovy#L42

Any advice here is appreciated! In the meantime I'll likely go back to using the old 'java' plugin

### PR DESCRIPTION
**Pull request by jmcampanini**
fixes #72

### CODE REVIEW

File: src/main/groovy/nebula/plugin/publishing/maven/MavenResolvedDependenciesPlugin.groovy [hunk 1]
```diff
@@ -39,14 +40,19 @@ class MavenResolvedDependenciesPlugin implements Plugin<Project> {
                             def dependencies = xml.asNode()?.dependencies?.dependency
                             def dependencyMap = [:]
 
-                            dependencyMap['runtime'] = project.configurations.runtime.incoming.resolutionResult.allDependencies
+                            dependencyMap['runtime'] = project
+                                    .sourceSets.main.runtimeClasspath.sources
```
Comment (rspieldenner) [inline src/main/groovy/nebula/plugin/publishing/maven/MavenResolvedDependenciesPlugin.groovy]: why from the sourceSets instead of from the configurations?

File: src/main/groovy/nebula/plugin/publishing/maven/MavenResolvedDependenciesPlugin.groovy [hunk 2]
```diff
@@ -39,14 +40,19 @@ class MavenResolvedDependenciesPlugin implements Plugin<Project> {
...
+                                    .flatten()
+
                             dependencyMap['test'] = project.configurations.testRuntime.incoming.resolutionResult.allDependencies - dependencyMap['runtime']
                             dependencies?.each { Node dep ->
                                 def group = dep.groupId.text()
                                 def name = dep.artifactId.text()
                                 def scope = dep.scope.text()
 
-                                if (scope == 'provided') {
+                                if (scope == 'provided' || scope == 'compile') {
```
Comment (rspieldenner) [inline src/main/groovy/nebula/plugin/publishing/maven/MavenResolvedDependenciesPlugin.groovy]: Not sure if this is a good idea. New java-library will separate api (which need to be in compile scope) and implementation which should be in runtime scope.

File: src/test/groovy/nebula/plugin/publishing/maven/MavenResolvedDependenciesPluginIntegrationSpec.groovy [hunk 3]
```diff
@@ -198,6 +198,38 @@ class MavenResolvedDependenciesPluginIntegrationSpec extends IntegrationSpec {
         d.version == '18.0'
     }
 
+    def 'works with java-library plugin and dependency-recommender'() {
```
Comment (rspieldenner) [inline src/test/groovy/nebula/plugin/publishing/maven/MavenResolvedDependenciesPluginIntegrationSpec.groovy]: good test

**Comment by rspieldenner** [comment]
also could you squash commits into 1

File: src/main/groovy/nebula/plugin/publishing/maven/MavenResolvedDependenciesPlugin.groovy (hunk 1 above)
Comment (jmcampanini) [inline src/main/groovy/nebula/plugin/publishing/maven/MavenResolvedDependenciesPlugin.groovy]: yea that's an oversight on my part, switched to directly using the configuration

File: src/main/groovy/nebula/plugin/publishing/maven/MavenResolvedDependenciesPlugin.groovy (hunk 2 above)
Comment (jmcampanini) [inline src/main/groovy/nebula/plugin/publishing/maven/MavenResolvedDependenciesPlugin.groovy]: i didn't like it either, but it passed all the tests. the new approach just makes another scope in the dependencyMap, so less manipulation, feels more right.

there may be edges here where we need to test out compileOnly and runtimeOnly configurations, but it seems out of scope of fixing the dependency-resolver issue

**Comment by jmcampanini** [comment]
squashed and updated. let me know if there's anything else i can do to make it better

**Comment by jmcampanini** [comment]
@rspieldenner lemme know if there's anything else missing from the PR
